import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from '@rspress/core';

const docsDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(docsDir, '..');

const { version } = JSON.parse(
  readFileSync(path.join(repoRoot, 'projects/ngx-virtual-dnd/package.json'), 'utf8'),
) as { version: string };

const SITE_ORIGIN = 'https://gultyayev.github.io';
const BASE = '/ngx-virtual-dnd/';
const REPO_URL = 'https://github.com/gultyayev/ngx-virtual-dnd';
const DESCRIPTION =
  'Angular drag and drop for virtual scrolling: sortable lists that stay fast with thousands of items.';

/**
 * Where `<LiveDemo>` iframes load the Angular examples from.
 * - Production: the demo app is deployed next to the docs, at `<base>demo/` (see scripts/assemble-site.js).
 * - Development: `npm start` serves the demo on :4200.
 * Override with the DEMO_URL environment variable (must end with `/`).
 */
const isBuild = process.argv.includes('build');
const DEMO_URL = process.env['DEMO_URL'] ?? (isBuild ? `${BASE}demo/` : 'http://localhost:4200/');

export default defineConfig({
  root: path.join(docsDir, 'pages'),
  outDir: path.join(repoRoot, 'dist/site'),
  themeDir: path.join(docsDir, 'theme'),
  base: BASE,
  siteOrigin: SITE_ORIGIN,
  lang: 'en',
  title: 'ngx-virtual-dnd',
  description: DESCRIPTION,
  icon: '/favicon.svg',
  logo: { light: '/logo-tile-light.svg', dark: '/logo-tile-dark.svg' },
  logoText: 'ngx-virtual-dnd',
  llms: true,
  markdown: {
    // Available in every MDX page without an import.
    globalComponents: [path.join(docsDir, 'components/LiveDemo.tsx')],
  },
  // The font stylesheet itself is imported by theme/index.css (works in dev too).
  head: [
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    ['meta', { name: 'theme-color', content: '#0e9488' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'ngx-virtual-dnd' }],
    ['meta', { property: 'og:image', content: `${SITE_ORIGIN}${BASE}og-image.png` }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ],
  builderConfig: {
    source: {
      define: {
        'process.env.DEMO_URL': JSON.stringify(DEMO_URL),
        'process.env.VDND_VERSION': JSON.stringify(version),
      },
    },
  },
  themeConfig: {
    // Nav comes from pages/_nav.json and the sidebar from _meta.json files; defining `nav`
    // here would switch off the autogenerated sidebar.
    socialLinks: [{ icon: 'github', mode: 'link', content: REPO_URL }],
    editLink: {
      docRepoBaseUrl: `${REPO_URL}/tree/master/docs/pages`,
    },
    footer: {
      message: 'Released under the MIT License.',
    },
    llmsUI: {
      placement: 'outline',
    },
    // Every page writes its own H1; the changelog's comes from the imported CHANGELOG.md.
    fallbackHeadingTitle: false,
  },
});
