import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, type UserConfig } from '@rspress/core';
import { transformerCompatibleMetaHighlight } from '@rspress/core/shiki-transformers';
import { rehypeApiDetails } from './plugins/rehype-api-details';

type ShikiTransformer = NonNullable<
  NonNullable<NonNullable<UserConfig['markdown']>['shiki']>['transformers']
>[number];

const docsDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(docsDir, '..');

const { version } = JSON.parse(
  readFileSync(path.join(repoRoot, 'projects/ngx-virtual-dnd/package.json'), 'utf8'),
) as { version: string };

const SITE_ORIGIN = 'https://gultyayev.github.io';
const BASE = '/ngx-virtual-dnd/';
const REPO_URL = 'https://github.com/gultyayev/ngx-virtual-dnd';
const DESCRIPTION =
  'Angular drag and drop for virtual scrolling: sortable lists that stay fast with thousands of items.';

/**
 * A code block that shows a file (` ```ts file="<root>/src/app/…" `) gets that path as its title,
 * unless it sets its own `title=`.
 */
const fileTitleTransformer: ShikiTransformer = {
  name: 'vdnd:file-title',
  pre(pre) {
    const meta = this.options.meta?.__raw ?? '';
    if (/(?:^|\s)title=/.test(meta)) return pre;
    const file = /(?:^|\s)file=["'`]?<root>\/([^"'`\s]+)/.exec(meta)?.[1];
    if (file) pre.properties = { ...pre.properties, title: file };
    return pre;
  },
};

/**
 * Where `<LiveDemo>` iframes load the Angular examples from.
 * - Production: the demo app is deployed next to the docs, at `<base>demo/` (see scripts/assemble-site.js).
 * - Development: `npm start` serves the demo on :4200.
 * Override with the DEMO_URL environment variable (must end with `/`).
 */
const isBuild = process.argv.includes('build');
const DEMO_URL = process.env['DEMO_URL'] ?? (isBuild ? `${BASE}demo/` : 'http://localhost:4200/');

export default defineConfig({
  root: path.join(docsDir, 'pages'),
  outDir: path.join(repoRoot, 'dist/site'),
  themeDir: path.join(docsDir, 'theme'),
  base: BASE,
  siteOrigin: SITE_ORIGIN,
  lang: 'en',
  title: 'ngx-virtual-dnd',
  description: DESCRIPTION,
  icon: '/favicon.svg',
  logo: { light: '/logo-tile-light.svg', dark: '/logo-tile-dark.svg' },
  logoText: 'ngx-virtual-dnd',
  llms: true,
  markdown: {
    // Available in every MDX page without an import.
    globalComponents: [path.join(docsDir, 'components/LiveDemo.tsx')],
    rehypePlugins: [rehypeApiDetails],
    shiki: {
      // Angular components keep their template in a `template:` string. The angular-ts grammar
      // is TypeScript plus Angular template highlighting inside it (plain ts shows one string).
      langs: ['tsx', 'ts', 'js', 'angular-ts', 'angular-html'],
      langAlias: { ts: 'angular-ts', typescript: 'angular-ts' },
      // `{3,5}` in a fence's meta highlights those lines.
      transformers: [transformerCompatibleMetaHighlight(), fileTitleTransformer],
    },
  },
  // English UI text that differs from Rspress's defaults.
  i18nSource: (source) => ({
    ...source,
    searchPlaceholderText: { ...source['searchPlaceholderText'], en: 'Search docs' },
    prevPageText: { ...source['prevPageText'], en: 'Previous' },
    nextPageText: { ...source['nextPageText'], en: 'Next' },
  }),
  // The font stylesheet itself is imported by theme/index.css (works in dev too).
  head: [
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    ['meta', { name: 'theme-color', content: '#0e9488' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'ngx-virtual-dnd' }],
    ['meta', { property: 'og:image', content: `${SITE_ORIGIN}${BASE}og-image.png` }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ],
  builderConfig: {
    source: {
      define: {
        'process.env.DEMO_URL': JSON.stringify(DEMO_URL),
        'process.env.VDND_VERSION': JSON.stringify(version),
      },
    },
  },
  themeConfig: {
    // Nav comes from pages/_nav.json and the sidebar from _meta.json files; defining `nav`
    // here would switch off the autogenerated sidebar.
    socialLinks: [{ icon: 'github', mode: 'link', content: REPO_URL }],
    editLink: {
      docRepoBaseUrl: `${REPO_URL}/tree/master/docs/pages`,
    },
    // Shown on the home page only.
    footer: {
      message: [
        '<span>Released under the MIT License.</span>',
        `<a href="${REPO_URL}">GitHub</a>`,
        '<a href="https://www.npmjs.com/package/ngx-virtual-dnd">npm</a>',
        `<a href="${BASE}llms.txt">llms.txt</a>`,
        `<a href="${BASE}llms-full.txt">llms-full.txt</a>`,
      ].join(''),
    },
    llmsUI: {
      placement: 'outline',
    },
    // Every page writes its own H1; the changelog's comes from the imported CHANGELOG.md.
    fallbackHeadingTitle: false,
  },
});
